DoctorConsultAppMVC/Models/ApointmentDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DoctorConsultAppMVC.Models
{
    public class ApointmentDetails
    {
        public int BookingId { get; set; }
        public int UserId { get; set; }
        public int DoctorId { get; set; }
        public string PatientName { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string Problem { get; set; }
        public string BookingDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    }
}

DoctorConsultAppMVC/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DoctorConsultAppMVC.Models
{
    public class Booking
    {
        public int UserId { get; set; }
        public int DoctorId { get; set; }
        public string PName { get; set; }
        public Gender Gender { get; set; }
        public string Age { get; set; }
        public string Problem { get; set; }
        public string BookingDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    }

    public enum Gender
    {
        Male,
        Female
    }
}

DoctorConsultAppMVC/Models/DoctorLogin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DoctorConsultAppMVC.Models
{
    public class DoctorLogin
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public int DoctorId { get; set; }


    }
}

DoctorConsultAppMVC/Models/PastConsultList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DoctorConsultAppMVC.Models
{
    public class PastConsultList
    {
        
        public int BookingId { get; set; }
        public int UserId { get; set; }
        public int DoctorId { get; set; }
        public string PatientName { get; set; }
        public string BookingDate { get; set; }
    }
}

DoctorConsultAppMVC/Models/PastConsultationDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DoctorConsultAppMVC.Models
{
    public class PastConsultationDetails
    {
        public int BookingId { get; set; }
        public int DoctorId { get; set; }
        public string PatientName { get; set; }
        public string BookingDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    }
}

DoctorConsultAppMVC/Models/UploadPrescription.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DoctorConsultAppMVC.Models
{
    public class UploadPrescription
    {
        public int BookingId { get; set; }
        public int DoctorId { get; set; }
        public int UserId { get; set; }
        public string prescription { get; set; }
        public string AdditionalSuggestion { get; set; }

    }
}

DoctorConsultAppMVC/Models/UserLogin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DoctorConsultAppMVC.Models
{
    public class UserLogin
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public int UserId { get; set; }

    }
}

DoctorConsultAppMVC/Models/UserProfile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DoctorConsultAppMVC.Models
{
    public class UserProfile
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string PhNo { get; set; }
        public string Email { get; set; }
    }
}

DoctorConsultAppMVC/Controllers/ConsultationController.cs
using DoctorConsultAppMVC.Models;
using Kendo.Mvc.Extensions;
using Microsoft.Build.Framework;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
namespace DoctorConsultAppMVC.Controllers
{
    public class ConsultationController : Controller
    {
        Uri baseadress = new Uri("http://localhost:4919/api/");
        HttpClient client;       
        public ConsultationController()
        {          
            client = new HttpClient();
            client.BaseAddress = baseadress;
        }
        // GET: Consultation
        public ActionResult DoctorLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DoctorLogin(DoctorLogin login)
        {
            try
            {
                var log = new DoctorLogin();
                HttpResponseMessage response = client.PostAsJsonAsync("DoctorConsultApp/DoctorLogin", login).Result;
                if (response.IsSuccessStatusCode)
                {
                    Session["Doctor"] = login.Email.ToString();
                    var data = DoctorbyEmail();
                    Session["DoctorId"] = data.DoctorId;
                    return RedirectToAction("BookedApointments");
                }
                else
                {
                    ViewData["Message"] = "Invalid Credentials.. Login Failed";
                }
                return View();
            }
            catch (Exception ex) { return View(ex); }                      
        }
        public ActionResult DoctorProfile()
        {
            if (Session["Doctor"] != null)
            {
                try
                {
                    var doctorlst = new DoctorModel();
                    HttpResponseMessage response = client.GetAsync("DoctorConsultApp/DoctorDetails?id=" + Session["DoctorId"]).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var data = response.Content.ReadAsStringAsync().Result;
                        doctorlst = JsonConvert.DeserializeObject<DoctorModel>(data);
                    }
                    return View(doctorlst);
                }
                catch (Exception ex){ return View(ex); }               
            }
            else
            {
                return RedirectToAction("DoctorLogin");
            }
        }
        public ActionResult BookedApointments()
        {
            if (Session["Doctor"] != null)
            {
                try
                {
                    List<BookedModel> doctorlst = new List<BookedModel>();
                    HttpResponseMessage response = client.GetAsync("DoctorConsultApp/List of Booked patients?id=" + Session["DoctorId"]).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var data = response.Content.ReadAsStringAsync().Result;
                        doctorlst = JsonConvert.DeserializeObject<List<BookedModel>>(data);
                    }
                    return View(doctorlst);
                }
                catch (Exception ex)
                {
                    return View(ex);
                }                
            }
            else
            {
                return RedirectToAction("DoctorLogin");
            }
        }
        public ActionResult ApointmentDetails(int id)
        {       
            if (Session["Doctor"] != null)
            {
                try
                {
                    var apointment = new ApointmentDetails();
                    HttpResponseMessage response = client.GetAsync("DoctorConsultApp/BookedDetails?id=" + id).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var data = response.Content.ReadAsStringAsync().Result;
                        apointment = JsonConvert.DeserializeObject<ApointmentDetails>(data);
                        Session["UserID"] = apointment.UserId;
                        Session["BookingID"] = apointment.BookingId;
                    }
                    return View(apointment);
                }
                catch (Exception ex)
                {
                    return View(ex);
                }               
            }
            else
            {
                return RedirectToAction("DoctorLogin");
            }
        }
        public ActionResult RegisterDoctor()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RegisterDoctor(DoctorRegistration doctor)
        {
            try
            {
                HttpResponseMessage response = client.PostAsJsonAsync("DoctorConsultApp/RegisterDoctor", doctor).Result;
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("DoctorLogin");
                }
                return View();
            }
            catch (Exception ex)
            {
                return View(ex);
            }          
        }
        public ActionResult UserLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UserLogin(UserLogin login)
        {
            try
            {
                HttpResponseMessage response = client.PostAsJsonAsync("DoctorConsultApp/UserLogin", login).Result;
                if (response.IsSuccessStatusCode)
                {
                    Session["User"] = login.Email;
                    var user = UserbyEmail();
                    Session["UserId"] = user.UserId;
                    Session["UserName"] = user.UserName;
                    var data = response.Content.ReadAsStringAsync().Result;
                    return RedirectToAction("UserHome", "Home");
                }
                else
                {
                    ViewData["Message"] = "Invalid Credentials.. Login Failed";
                }
                return View();
            }
            catch (Exception ex)
            {
                return View(ex);
            }          
        }
        public ActionResult RegisterUser()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RegisterUser(UserRegistration doctor)
        {
            try
            {
                HttpResponseMessage response = client.PostAsJsonAsync("DoctorConsultApp/RegisterUser", doctor).Result;
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("UserLogin");
                }
                return View();
            }
            catch (Exception ex)
            {
                return View(ex);
            }           
        }
        public ActionResult UserProfile()
        {
            if (Session["User"] != null)
            {
                try
                {
                    var user = new UserProfile();
                    HttpResponseMessage response = client.GetAsync("DoctorConsultApp/UserProfile?Userid=" + Session["UserId"]).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var data = response.Content.ReadAsStringAsync().Result;
                        user = JsonConvert.DeserializeObject<UserProfile>(data);
                    }
                    return View(user);
                }
                catch (Exception ex)
                {

                    return View(ex);
                }
                
            }
            else
            {
                return RedirectToAction("UserLogin");
            }
        }
        public ActionResult GetdoctorList()
        {
            if (Session["User"] != null)
            {
                try
                {
                    List<DoctorModel> doctorlst = new List<DoctorModel>();
                    HttpResponseMessage response = client.GetAsync("DoctorConsultApp/ListOfDoctors").Result;
                    if (response.IsSuccessStatusCode)
                    {
                        string data = response.Content.ReadAsStringAsync().Result;
                        doctorlst = JsonConvert.DeserializeObject<List<DoctorModel>>(data);

                    }
                    return View(doctorlst);
                }
                catch (Exception ex)
                {
                    return View(ex);
                }              
            }
            else
            {
                return RedirectToAction("UserLogin");
            }
        }
        //Get doctor detailes by id
        public ActionResult Search(int id)
        {
            if (Session["User"] != null)
            {
                try
                {
                    var doctorlst = new DoctorModel();
                    HttpResponseMessage response = client.GetAsync("DoctorConsultApp/DoctorDetails?id=" + id).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var data = response.Content.ReadAsStringAsync().Result;
                        doctorlst = JsonConvert.DeserializeObject<DoctorModel>(data);
                        Session["DoctorIdforbooking"] = doctorlst.DoctorId;
                    }
                    return View(doctorlst);
                }
                catch (Exception ex)
                {

                    return View(ex);
                }
                
            }
            else
            {
                return RedirectToAction("UserLogin");
            }
        }
        public ActionResult PastConsultList()
        {
            if (Session["User"] != null)
            {
                try
                {
                    var pastconsults = new List<PastConsultList>();

DoctorConsultAppMVC/Views/Consultation/ApointmentDetails.cshtml
@model DoctorConsultAppMVC.Models.ApointmentDetails
@{
    ViewBag.Title = "ApointmentDetails";
}
<div class="k-form-horizontal">
    <div class="k-form-horizontal">
        <div class="k-fab-dark" style="color:blue; text-align:center;">
            <h4>Apointment Details</h4>
        </div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserId)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.UserId)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.PatientName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PatientName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Gender)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Gender)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Age)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Age)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Problem)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Problem)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.BookingDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.BookingDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.StartTime)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StartTime)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.EndTime)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.EndTime)
            </dd>
        </dl>
        <div>
            <div>
                <button class="k-button">
                    @Html.ActionLink("Back to List", "BookedApointments"@*, new { id = Model.DoctorId }*@)
                </button>
                <button class="k-button">
                    @Html.ActionLink("Add Prescription", "UploadPrescription"@*, new { id = Model.DoctorId }*@)
                </button>
            </div>
        </div>
    </div>
 </div>

DoctorConsultAppMVC/Views/Consultation/BookedApointments.cshtml
@model IEnumerable<DoctorConsultAppMVC.Models.BookedModel>

@{
    ViewBag.Title = "BookedApointments";
}

<h2>Booked Apointments</h2>


<div class="row">
    <div class="col-12">
        @(Html.Kendo().Grid<DoctorConsultAppMVC.Models.BookedModel>(Model)
                             .Name("grid")
                             .Columns(column=>
                             {
                                 column.Bound(p => p.UserId);
                                 column.Bound(p => p.PName);
                                 column.Bound(p => p.BookingDate);
                                 column.Bound(p => p.StartTime);
                                 column.Bound(p => p.EndTime);
                                 column.Bound(c => c.BookingId).Title("Details").ClientTemplate(
                                                         @Html.ActionLink("Details", "ApointmentDetails", "Consultation", new { id = "#=BookingId#" }, htmlAttributes: null).ToHtmlString()
                                  );

                             })
                             .Pageable()
                             .Sortable()
                             .Navigatable()
                             .Resizable(r => r.Columns(true))
                             .Filterable()
                             .Scrollable()
                             .DataSource(dataSource => dataSource
                                      .Ajax()
                                      .PageSize(20)
                                      .Read(read => read.Action("GetdoctorList", "DoctorConsultAppController")))
                   )
    </div>
</div>

DoctorConsultAppMVC/Views/Consultation/Booking.cshtml
@using DoctorConsultAppMVC.Models
@model Booking

@{
    ViewBag.Title = "Booking";
}
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

 <div class="k-form-horizontal">
    <div style="background-color:aliceblue; border:groove;border-radius: 8px;">
        <div class="k-fab-dark" style="color:blue; text-align:center;">
            <h4>Booking Form</h4>
        </div>
        <hr />
        <div class="k-form-group" style="margin:0 0 0 10px;">
            <div class="k-col-md-10">
                @(Html.Kendo().TextBoxFor(model => model.PName)
                      .Name("PName")
                      .Label(label=>label.Content("PName").Floating(true))
                      .HtmlAttributes(new { placeholder = " Name", @class = "form-control", required = "required", style = "width: 162%;border-radius: 8px;border-color: #3480eb ;" })
           )
            </div>
        </div>
        <br />
        <div class="k-form-group" style="margin:0 0 0 10px;">
            <div class="k-col-md-10">
                @(Html.DropDownListFor(m => m.Gender,
            new SelectList(Enum.GetValues(typeof(Gender))),
            "Select Gender", new { @class = "form-control", style = "width: 120%;border-radius: 8px;border-color: #3480eb ;" })
        )
            </div>
        </div>

        <div class="k-form-group" style="margin:0 0 0 10px;">
            <div class="k-col-md-10">
                @(Html.Kendo().TextBoxFor(model => model.Age)
                      .Name("Age")
                      .Label(label=>label.Content("Age").Floating(true))
                      .HtmlAttributes(new { placeholder = " Age", @class = "form-control", required = "required", style = "width: 162%;border-radius: 8px;border-color: #3480eb ;" })
           )
            </div>
        </div>

        <div class="k-form-group" style="margin:0 0 0 10px;">
            <div class="k-col-md-10">
                @(Html.Kendo().TextBoxFor(model => model.Problem)
                      .Name("Problem")
                      .Label(label=>label.Content("Problem").Floating(true))
                      .HtmlAttributes(new { placeholder = " Problem", @class = "form-control", required = "required", style = "width: 162%;border-radius: 8px;border-color: #3480eb ;" })
           )
            </div>
        </div>

        @*<div class="form-group" style="margin:0 0 0 10px;">
            <div class="k-col-md-10">
                @(Html.Kendo().TextBoxFor(model => model.BookingDate)
                      .Name("BookingDate")
                      .Label(label=>label.Content("BookingDate").Floating(true))
                      .HtmlAttributes(new { placeholder = " BookingDate", @class = "form-control", required = "required", style = "width: 162%;border-radius: 8px;border-color: #3480eb ;" })
           )
            </div>
        </div>

        <div class="form-group" style="margin:0 0 0 10px;">
            <div class="k-col-md-10">
                @(Html.Kendo().TextBoxFor(model => model.StartTime)
                      .Name("StartTime")
                      .Label(label=>label.Content("StartTime").Floating(true))
                      .HtmlAttributes(new { placeholder = " StartTime", @class = "form-control", required = "required", style = "width: 162%;border-radius: 8px;border-color: #3480eb ;" })
           )
            </div>
        </div>

        <div class="form-group" style="margin:0 0 0 10px;">
            <div class="k-col-md-10">
                @(Html.Kendo().TextBoxFor(model => model.EndTime)
                      .Name("EndTime")
                      .Label(label=>label.Content("EndTime").Floating(true))
                      .HtmlAttributes(new { placeholder = " EndTime", @class = "form-control", required = "required", style = "width: 162%;border-radius: 8px;border-color: #3480eb ;" })
           )
            </div>
        </div>*@
        <br />

        <div class="k-form-group">
            <div class="k-col-md-offset-2 col-md-10">
                <input type="submit" value="submit" class="btn btn-primary" />
            </div>
            <div>
                @Html.ActionLink("Back to Doctor List", "GetdoctorList")
            </div>
        </div>
    </div>    
 </div>
}

<script>
$(function () {
$("form").kendoValidator();
});
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoctorConsultAppMVC/Views/Consultation/DoctorLogin.cshtml
@model DoctorConsultAppMVC.Models.DoctorLogin

@{
    ViewBag.Title = "DoctorLogin";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="k-form-horizontal">
    <div class="k-fab-dark" style="text-align: center; color: blue; ">
    <h4>DoctorLogin</h4>
         <div>
        <img src="~/images/doctor.png" alt="Smiley face" width="55" height="45" style="border:1px solid black" />
        </div>
    </div>
    <br />
    
    <div style=" text-align:center; background-color:aliceblue; margin:0 0 0 5px; border:groove;">
        <div class="k-form-group">
            <div class="k-col-md-10">
                @(Html.Kendo().TextBoxFor(model => model.Email)
                      .Name("Email")
                      .Label(label=>label.Content("Email").Floating(true))
                      .HtmlAttributes(new { placeholder = " Email", @class = "form-control", required = "required", style = "width: 120%;border-radius: 8px;border-color: #3480eb ;" })
           )
            </div>
        </div>
        <div class="k-form-group">
            <div class="k-col-md-10">
                @(Html.Kendo().TextBoxFor(model => model.Password)
                      .Name("Password")
                      .Label(label=>label.Content("Password").Floating(true))
                      .HtmlAttributes(new { placeholder = " Password", @class = "form-control", type="Password",required = "required", style = "width: 120%;border-radius: 8px;border-color: ##3480eb;" })
           )
            </div>
        </div>
        <div class="form-group">
            <div class="k-col-md-10" style="color:red">
                <div id="alertmsg">
                    @ViewData["Message"]

                </div>
            </div>
        </div>

        <div class="k-form-group">
            <div class="k-col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary">Login</button>
            </div>
            <div>
                @Html.ActionLink("Register Here", "RegisterDoctor")
            </div>
        </div>
    </div>
</div>
}


<script>

    $('#alertmsg'){
        alert("Login Filed !");
    }
   
</script>
<script>
    $(function () {
        $("form").kendoValidator();
    });
</script>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoctorConsultAppMVC/Views/Consultation/DoctorProfile.cshtml
@model DoctorConsultAppMVC.Models.DoctorModel

@{
    ViewBag.Title = "DoctorProfile";
}



<div>
  
    <div class="k-fab-dark" style="text-align: center; color: blue; ">
        <h4>Profile</h4>
        <div>
            <img src="~/images/doctor.png" alt="Smiley face" width="55" height="45" style="border:1px solid black" />
        </div>
    </div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DoctorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Specilization)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Specilization)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DoctorConsultAppMVC/Views/Consultation/GetPrescription.cshtml
@model DoctorConsultAppMVC.Models.DownloadPrescription
@{
    ViewBag.Title = "GetPrescription";
}
<br />
<div class="k-form-horizontal">
    <div style="text-align:; background-color:aliceblue; border:groove;border-radius: 8px;">
        <h4 style="text-align:center;">Prescription Details</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.Label("Prescription :")
            </dt>
            <dd>
                <img src="@Url.Content(Model.Prescription)" width="250" height="250" />
            </dd>
            <br />
            <dt>
                @Html.Label("Additinal Comments :")
            </dt>
            <dd>              
                @Html.DisplayFor(model => model.AdditionalSuggestion)
            </dd>
        </dl>
        <br />
        <dl>
            <dt>
                <div style=" margin: 0 0 0 80px">
                    <button> @Html.ActionLink("Back to Home", "UserHome","Home")</button>
                </div>              
            </dt>      
        </dl>
    </div>
</div>

DoctorConsultAppMVC/Views/Consultation/PastConsultList.cshtml
@model IEnumerable<DoctorConsultAppMVC.Models.PastConsultList>

@{
    ViewBag.Title = "PastConsultList";
}
    <div class="k-fab-dark" style="color:blue; text-align:center;">
        <h4>Past ConsultationList</h4>
    </div>

        <div class="row">
            <div class="col-12">

                @(Html.Kendo().Grid<DoctorConsultAppMVC.Models.PastConsultList>(Model)
                             .Name("grid")
                             .Columns(column=>
                             {
                                 column.Bound(p => p.BookingId);
                                 column.Bound(p => p.DoctorId);
                                 column.Bound(p => p.PatientName);
                                 column.Bound(p => p.BookingDate);
                                 column.Bound(c => c.BookingId).Title("Details").ClientTemplate(
                                                         @Html.ActionLink("Details", "PastConsultationDetails", "Consultation", new { id = "#=BookingId#" }, htmlAttributes: null).ToHtmlString()
                                  );

                             })
                             .Pageable()
                             .Sortable()
                             .Navigatable()
                             .Resizable(r => r.Columns(true))
                             .Filterable()
                             .Scrollable()
                             .DataSource(dataSource => dataSource
                                      .Ajax()
                                      .PageSize(20)
                                      .Read(read => read.Action("GetdoctorList", "DoctorConsultAppController")))

                   )

            </div>

        </div>

DoctorConsultAppMVC/Views/Consultation/UploadPrescription.cshtml
@model DoctorConsultAppMVC.Models.UploadPrescription

@{
    ViewBag.Title = "UploadPrescription";
}
<br />
@using (Html.BeginForm("UploadPrescription","Consultation",FormMethod.Post,new { enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
<div style="background-color:#d9ffb3;border:groove;border-radius: 10px;text-align:center;">
    <div class="form-horizontal">
        <h4>UploadPrescription</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.prescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" required>
            @*@(Html.Kendo().TextBoxFor(model => model.prescription)
                    .Name("prescription")
                    .Label(label=>label.Content("Prescription").Floating(true))
                    .HtmlAttributes(new { placeholder = " Prescription", @class = "form-control", type="Password",required = "required", style = "width: 120%;border-radius: 8px;border-color: ##3480eb;" })
            )*@

        </div>
    </div>
        <div class="k-form-group">
            <div class="col-md-10">
                @(Html.Kendo().TextBoxFor(model => model.AdditionalSuggestion)
                      .Name("AdditionalSuggestion")
                      .Label(label=>label.Content("Suggestion").Floating(true))
                      .HtmlAttributes(new { placeholder = " Suggestion", @class = "form-control",required = "required", style = "width: 120%;border-radius: 8px;border-color: ##3480eb;" })
              )
            </div>
        </div>
        <div class="form-group" style="margin: 0 0 10px">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </div>
    </div>
</div>
}
<script>
$(function () {
$("form").kendoValidator();
});
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}